channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.6.1
  - nodejs=16.13.1
  - pip=23.0.1
  - python_abi=3.10
  - r-irkernel=1.3
  - r-base=4.1.1
  - r-essentials=1.7.0
  - pyarrow=9.0.0
  - tiledb
  - tiledbvcf-py
  - dask-jobqueue
  - pip:
    - numpy==1.24.2
    - pandas==1.5.3

