name: jupyterlab_launcher
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4.4
  - nodejs=16.13.1
  - pip=22.1.2
  - pyarrow=9.0.0
  - python_abi=3.10
  - r-irkernel=1.3
  - pip:
    - numpy==1.23.4
    - pandas==1.5.0

